# Generated by Django 4.2 on 2023-04-16 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Model',
            fields=[
                ('student_id', models.IntegerField(primary_key=True, serialize=False)),
                ('student_fname', models.CharField(max_length=30)),
                ('student_lname', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('grade', models.IntegerField()),
            ],
        ),
    ]
